<?php
/**
 * @package InsightCustom
 */
get_header();
?>
<div id="primary" class="content-area">
	<main id="main" class="site-main">
		<section id="privacyPolicy">
		  <div class="pageWidth">
	      <div class="projectTitleWrapper">
	        <h1 class="primaryText">Privacy Policy</h1>
	      </div>
	      <p>
	      By accessing or using Fox Structures' website, you agree to the terms of this Online Privacy Policy, as outlined below. If you do not agree to these terms, please do not access or use this site.
	      </p>
	      <h3>Collection of Personal Information</h3>
	      <p>
	        When you merely use the website for informational purposes, i.e. if you do not log in to use the website, register or otherwise provide us with information, we do not collect any personal data, except for the data transmitted by your browser that enables you to access the website. This includes:
	      </p>
	      <ul>
	        <li>IP address</li>
	        <li>Date and time of the request</li>
	        <li>Content of the request (specific site)</li>
	        <li>Access status / HTTP status code</li>
	        <li>Volume of data transmitted each time</li>
	        <li>Website from which the request comes</li>
	        <li>Browser</li>
	        <li>Operating system and its interface</li>
	        <li>Language and version of the browser software</li>
	        <li>Your country of origin</li>
	      </ul>
	      <p>
	      When you engage in certain activities on this site, you may be asked to provide certain information about yourself by filling out and submitting an online form. It is completely optional for you to engage in these activities.
	      If you elect to engage in these activities, however, you may be required to provide personal information, such as your name, mailing address, e-mail address and other personal identifying information.
	      </p>
	      <h3>Use of the “Contact” Page</h3>
	      <p>
	      When you contact Fox Structures via email or via the contact form, Fox Structures will store your email address and, if you have provided them, your name and phone number in order to answer your questions.
	      </p>
	      <p>
	      When you submit personal information, you understand and agree that Fox Structures may transfer, store and process your information in any of the countries in which Fox Structures maintain offices, including without limitation, the United States.
	      </p>
	      <p>
	      Fox Structures collects this information in order to record and support your participation in the activities you select. Fox Structures also uses information that you provide as part of our effort to keep you informed about product upgrades,
	      special offers and other Fox Structures products and services. Fox Structures will never sell or share your information with other companies.
	      </p>
	      <h3>Embedded Content From Other Websites</h3>
	      <p>
	      Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.
	      </p>
	      <p>
	      These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.
	      </p>
	      <h3>Analytics</h3>
	      <p>
	      This website uses Google Analytics to help analyze how visitors use this site. Google Analytics uses “cookies”, which are small text files placed on your computer, to collect standard internet log information and visitor behavior information in an
	      anonymous form. Note the deliberate emphasis of anonymous, as no personally identifiable information, is collected about you unless you explicitly submit that information on this website.
	      </p>
	      <p>
	      The anonymous information generated by Google Analytics cookies about your use of this website is transmitted to Google—not Fox Structures. This information is processed to compile statistical reports on website activity for this site only.
	       Fox Structures uses these reports to evaluate aggregate visitor usage so that we can optimize the content, and its marketing, to better meet your needs. This is essential for Fox Structures to operate this website as a free-to-use service.
	      </p>
	      <h2 class="primaryText">Cookie Policy</h2>
	      <p>
	      A cookie is a small file containing data which is saved to the computer or device you're using when you visit a website. When you return to a website, these cookies are read by that site and often used to identify you and your preferences. No personal information, such as your name or address, is stored in cookies.
	      </p>
	      <p>
	      Remember that as cookies are device based, if you use our website on your desktop and on your mobile, cookies will be saved to both devices.
	      </p>
	      <h4>
	      Types of Cookies
	      </h4>
	      <p>
	      There are different types of cookies we use depending on what we need them for.
	      </p>
	      <h4>
	      Persistent vs. Session Cookies
	      </h4>
	      <p>
	      A cookie can either be persistent (long-term) or session (short-term) based. We use both. Persistent cookies remain on your device after you have closed your browser window.
	      These cookies are used to remember you when you next return to a website, or for remarketing purposes so that when you are on a different website we can show you an advertising banner.
	      Persistent cookies stay on your browser until their expiry date or if you should decide to delete them, which you can do through your browser.
	      </p>
	      <p>
	      A session cookie only stays on your browser for as long as you are using a particular website; it is deleted as soon as you close the browser. Session cookies are needed, among other things,
	      to remember who you are when you move from page to page on a website.
	      </p>
	      <h4>
	      First and Third-Party Cookies
	      </h4>
	      <p>
	      A cookie can also be a first-party cookie or a third-party cookie. First-party cookies are those set by the website you visited. All other cookies are third-party. We use both.
	      We only work with trusted partners when using third party cookies. These include performance cookies, which help us track visits or revenue to partner websites, analytics cookies
	      (i.e. Google Analytics) which help us understand how much web traffic or app traffic we are receiving, and marketing cookies (i.e. Facebook, Google) which help us track
	      the performance of our marketing campaigns, remarket similar products or services to you (including via social media), and create 'lookalike' audiences to find new customers.
	      If you view content (i.e. video) powered by a third-party on our website (i.e. YouTube) they will set their own cookies on your browser. All our partners have their own cookie policies, which you can refer to.
	      </p>
	      <h4>
	      The Third-Party Cookies we use
	      </h4>
	      <p>
	      Below is a sample of significant third-party cookies we use on our website for the purposes of analysis or marketing.
	      </p>
	      <p>
	      We use Google Analytics to analyze the use of our website. Google Analytics gathers information about how our website is used by means of cookies. The information gathered relating to
	      our website is used to create reports about the use of our website. View <a href="https://policies.google.com/privacy?hl=en&gl=uk" target="_blank" class="primaryLink">Google's privacy policy.</a>
	      </p>
	      <h4>
	      Why we use cookies
	      </h4>
	      <p>
	      There are many different reasons we collect cookies, including:
	      </p>
	      <p><b>
	      Functionality:</b> To remember the preferences you set on our website, for example, if you're logged in or not, or if you've accepted our cookie policy, so that we can create the experience you're expecting
	      </p>
	      <p><b>
	      Understanding our Customers:</b> To track all the pages you visit and buttons you click on, so we can understand what is relevant to you and therefore create a more personalized experience for you
	      </p>
	      <p><b>
	      Personalization:</b> To link what we know about you (as our customer) to your behavior on our website so that we can understand more about you and create a more personalized experience for you
	      </p>
	      <p><b>
	      Marketing:</b> To market new products or features to you via other channels like social media, and to create similar audience profiles (sometimes called 'lookalike audiences') we can market to, so we can target advertising to new customers
	      </p>
	      <p><b>
	      Third-party Connections:</b> To help you navigate third-party content on our site, to help their marketing and analysis or where the third party is our service provider and uses cookie data to provide us with insights into our website and how people use it
	      </p>
	      <h4>
	      How to Manage Your Cookies
	      </h4>
	      <p>
	      You can choose to accept or decline cookies through your web browser. If you choose to decline cookies this can reduce your experience using many websites.
	      You can also delete existing cookies through your web browser.
	      </p>
	      <p>
	      For information about how to manage cookies for individual browsers, here are relevant resources:
	      </p>
	      <p>
	        <a href="https://support.google.com/chrome/answer/95647?hl=en&" target="_blank" class="primaryLink">Google Chrome</a><br>
	        <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank" class ="primaryLink">Firefox</a><br>
	        <a href="https://www.opera.com/help/tutorials/security/cookies/" target="_blank" class="primaryLink">Opera</a><br>
	        <a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank" class="primaryLink">Internet Explorer</a><br>
	        <a href="https://support.apple.com/kb/PH21411?locale=en_US" target="_blank" class="primaryLink">Safari</a><br>
	        <a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy" target="_blank" class="primaryLink">Edge</a><br>
	      </p>
		  </div>
		</section>
	</main>
</div>
<?php
get_footer();
